### ISSUE TITLE
Is rweekly live broken?

### ISSUE THREAD

**Issue by gadenbuie** [rweekly/rweekly.org#1017]
Today is 2021-12-20 and the last post in [the rweekly live RSS feed](https://feeds.feedburner.com/rweekly-live) is from 2021-12-13.

![image](https://user-images.githubusercontent.com/5420529/146808841-a3ff27be-678c-48d2-ad11-7ade032f9847.png)

At <https://rweekly.org/live> I only see two posts from November 2021:

![image](https://user-images.githubusercontent.com/5420529/146808966-51c44c1d-76ce-4f8e-8e82-cc3857610b73.png)

**Comment by jonocarroll** [comment]
Sorry to report that yes, something is wrong. We are aware of a bitcoin miner running on some of our infrastructure which may be a cause of some of the issues, but at the moment we are in a broken state. We have decided to take a break over the holidays and fingers crossed we will be back online at the start of the new year.

**Comment by yihui** [comment]
It seems to have stopped working again (https://rweekly.org/live). The last item was from June last year:

![image](https://user-images.githubusercontent.com/163582/208983457-5f4e401b-8ae6-4a02-8408-6b6115939d7a.png)

---

The Twitter account [`@rweekly_live`](https://twitter.com/rweekly_live) also stopped updating at that time.

BTW, the page https://rweekly.org/feedlist.html doesn't show any feeds at all.

**Comment by jonocarroll** [comment]
Correct - we are still in the process of rebuilding our infrastructure, so our RSS feed is not currently working. The list of feeds we currently source from is https://github.com/rweekly/rweekly.org/blob/gh-pages/rss_feeds.csv and we welcome PRs to add to that. 

We still collect any tweets tagged with @rweekly_submit but we're trialling collecting any toots on Mastodon tagged with #rweekly_submit (work in progress). Posting to Twitter will remain offline at least in the short term.

I've started a discussion to see if we can get something up and running again: https://github.com/rweekly/rweekly.org/discussions/1236

**Comment by yihui** [comment]
Sounds good. Thanks for the information!
