### ISSUE TITLE
No more updates since early december 2021?

### ISSUE THREAD

**Issue by ekianjo** [rweekly/rweekly.org#1021]
Just wondering what's happening, it's been at least 2-3 weeks without updates.

**Comment by jonocarroll** [comment]
We're experiencing some issues with our infrastructure, and decided to take a break over the holidays.

We'll hopefully have a bumper issue in the next couple of weeks.

**Comment by andrewbulin** [comment]
> We're experiencing some issues with our infrastructure, and decided to take a break over the holidays.
> 
> 
> 
> We'll hopefully have a bumper issue in the next couple of weeks.

Anything we can help with?
Thanks for all the hard work! ^_^

**Comment by oude-gao** [comment]
Am wondering here too, let me know if I could help!

**Comment by jonocarroll** [comment]
We're a little stuck at the moment as our infrastructure is tied up with a significant member we haven't seen for some time.

We are looking into getting an issue out with the submissions we have, and appreciate everyone's patience and kind offers.

**Comment by rpodcast** [comment]
RWeekly has resumed starting with issue 2022-W13: https://rweekly.org/2022-W13.html . While not everything in our backend is in a working state yet, we will rely on pull requests and submissions to the RWeekly twitter bot [`@rweekly_submit`](https://twitter.com/rweekly_submit) .
