### ISSUE TITLE
Make 'Grants & Funding' permanent?

### ISSUE THREAD

**Issue by HenrikBengtsson** [rweekly/rweekly.org#1057]
Hi, I added the new section 'Grants & Funding' to [R Weekly 2022-W15](https://rweekly.org/2022-W15.html), where it lists:

> * R Consortium [ISC Call for Proposals](https://www.r-consortium.org/blog/2022/04/01/isc-call-for-proposals-2) looking to provide grants for technical projects that will have a significant impact on the R Community. Deadline 2022-05-01 ( r-consortium.org ) 
>
> * R Consortium [New R User Groups, Conferences, and Training Program](https://www.r-consortium.org/announcement/2022/04/01/announcing-the-new-r-user-groups-conferences-and-training-program). Deadline 2022-09-30 ( r-consortium.org )

In the reset [draft.md](https://github.com/rweekly/rweekly.org/blob/gh-pages/draft.md), I noticed that this section has been dropped.  I'd like to propose:

1. Make 'Grants & Funding' permanent, similarly to 'Upcoming Events in 3 Months'
2. Keep listed grants as long as they're available/relevant, similarly to events are kept in 'Upcoming Events in 3 Months'

After some exposure of this section, my hope is that other funding sources will identified and listed here too.

**Comment by jonmcalder** [comment]
Apologies @HenrikBengtsson this was an oversight on my part when resetting the draft - I agree with your suggestion and have amended the draft accordingly.

Thanks for following up!
