### ISSUE TITLE
Suggestion: BioC -> Bioconductor

### ISSUE THREAD

**Issue by HenrikBengtsson** [rweekly/rweekly.org#1101]
May I suggest renaming header 'BioC' to 'Bioconductor', because it's "Bioconductor" is _not_ "BioConductor".

PS. I've tried to do this with my PR's, but it's been dropped each time.

**Comment by BatoolMM** [comment]
Thank you @HenrikBengtsson for pointing this out. We'll make sure it's renamed in the upcoming issue.
