### ISSUE TITLE
PR template

### ISSUE THREAD

**Issue by maelle** [rweekly/rweekly.org#117]
I see you have a PR template (and also an issue template) but then it's not related to anything in the [contributing guide](https://github.com/rweekly/rweekly.org/blob/gh-pages/CONTRIBUTING.md) so I wasn't sure for instance how to justify/not justify the links I was adding? And here in the issue template likewise I am not sure I am doing things right. 😹 

Thanks for a great newsletter!

**Comment by jonmcalder** [comment]
Thanks Maëlle! This is a good point. With regards to PR's - in general links that pertain directly to R shouldn't need justification, it's just a case of getting them into the right category for the sake of consistency.

I think the info you were looking for is probably more likely to be found [here in the wiki](https://github.com/rweekly/rweekly.org/wiki) and as it happens this is something I raised internally with the team last week that we should make more visible - we just haven't got around to it yet.

We'll also look into improving the PR and issue templates.

**Comment by maelle** [comment]
Great, thanks! :smile_cat:

**Comment by jonmcalder** [comment]
Thanks for working on this Maëlle!
