### ISSUE TITLE
Not receiving RWeekly newsletter anymore

### ISSUE THREAD

**Issue by audricvigier** [rweekly/rweekly.org#1180]
I noticed I am not receiving the newsletter since July, despite the blog still being active. I unsubscribed and then re-subscribed a few weeks ago to see if it would would fix it, but it didn't. My colleagues are having the same problem.

**Comment by jonocarroll** [comment]
Thanks for letting us know. It's not on your side; something isn't working and we don't currently have access to that infrastructure. We're working on an alternative solution, but for now it means checking the website each week is the only option.

**Comment by jonocarroll** [comment]
It seems this is because Google killed Feedburner email subscriptions: https://9to5google.com/2021/04/14/google-feedburner-email/

We're working on getting the newsletter up and running again with a different service.
