### ISSUE TITLE
Submit a new RSS feed 

### ISSUE THREAD

**Issue by dieghernan** [rweekly/rweekly.org#1210]
Hi:

I would like to submit my blog RSS feed to Rweekly, however I can’t see how on the link <https://rweekly.org/submit>.

The RSS to add would be <https://dieghernan.github.io/rweekly.xml>, I checked and it is valid:

<https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdieghernan.github.io%2Frweekly.xml>

**Comment by jonocarroll** [comment]
Hi, we're still reconnecting some of our infrastructure. You can add your feed to this file: https://github.com/rweekly/rweekly.org/blob/gh-pages/rss_feeds.csv with a pull request. Cheers!
