### ISSUE TITLE
R Weekly title week numbers are now off by one, e.g. today's 2023-W01 should have been 2023-W02

### ISSUE THREAD

**Issue by HenrikBengtsson** [rweekly/rweekly.org#1245]
The last two R Weekly news issues had titles:

* R Weekly 2022-W52 (released Monday 2023-01-02)
* R Weekly 2023-W01 (released Monday 2023-01-09)

Now, if the titles are meant to show the week number of the week that just completed, those are correct. However, in the past, the week number was referring to the week that just started.  See also https://github.com/rweekly/rweekly.org/issues/798#issuecomment-752844830.

So, I think the next news issue, to be released on Monday 2023-01-16, should be:

* R Weekly 2023-W03

**Comment by jonocarroll** [comment]
I'm on board with this definition. The important part is being consistent. We could simply rename the existing posts
```
2023-01-02-2022-W52.md -> 2023-01-02-2023-W01.md
2023-01-09-2023-W01.md -> 2023-01-09-2023-W02.md
```
then continue with 
```
2023-01-16-2023-W03.md
```

**Comment by HenrikBengtsson** [comment]
A friendly reminder about this one
