### ISSUE TITLE
Email subscription link is broken

### ISSUE THREAD

**Issue by joeroe** [rweekly/rweekly.org#1268]
The "Mail" link in the nav of https://rweekly.org and the link in "Subscribe R Weekly with [Email](https://feedburner.google.com/fb/a/mailverify?uri=rweekly&loc=en_US)." in the footer both lead to https://feedburner.google.com/fb/a/mailverify?uri=rweekly&loc=en_US, which is a 404.

**Comment by jonocarroll** [comment]
Thanks. Feedburner is no longer active, so we're in a bit of a holding pattern while we coordinate some new delivery mechanism. See https://github.com/rweekly/rweekly.org/issues/1180#issuecomment-1312837679
