### ISSUE TITLE
Broken link to "mail"

### ISSUE THREAD

**Issue by matanhakim** [rweekly/rweekly.org#1310]
When clicking on the [mail](https://feedburner.google.com/fb/a/mailverify?uri=rweekly&loc=en_US) hyperlink in the [rweekly.org](https://rweekly.org/) top navbar, it presents a 404 error:
![image](https://user-images.githubusercontent.com/111883851/230569043-d5c18c00-3633-41dc-b7a7-b10b069a7c77.png)

**Comment by tonyelhabr** [comment]
Yes, I believe this is the same issue mentioned in #1268. I'm not sure we'll have the feed fixed any time soon. One solution may be to remove the button on the page until we have the feed link fixed.

I'll discuss with the rest of the RWeekly team.

**Comment by matanhakim** [comment]
Thanks, and much appreciation for all of your work in RWeekly!

**Comment by tonyelhabr** [comment]
Seems like the team is ok with removing the link. I will try to get to it sometime this week.

**Comment by tonyelhabr** [comment]
Removed mail link with #1319
