### ISSUE TITLE
Does RSS feed submission still work?

### ISSUE THREAD

**Issue by harshvardhaniimi** [rweekly/rweekly.org#1315]
The ReadMe on Github repository takes me to [this page](https://rweekly.org/submit), which only has details for one-off submission or submission via tweets. Is the option to add an RSS feed of blogs not valid now?

If I'm mistaken, please correct me. I would like to add my following blogs on R Weekly:
- [Next — Today I Learnt About Data Science](https://harsh17.in/next)
- [R Blogs](https://www.harsh17.in/categories/r/). The RSS link is https://rss.app/feeds/VMOHB288uNbKSsVi.xml

Thanks!

### Screenshot

<img width="1037" alt="Screenshot 2023-04-10 at 9 27 40 PM" src="https://user-images.githubusercontent.com/40472851/231031524-fa610aff-4a39-447e-9d41-0de051a85853.png">

**Comment by tonyelhabr** [comment]
We're happy to take RSS submissions, e.g. #1303.

- Regarding your first link, is there an RSS feed you link us to?
- Regarding your second link, the RSS feed doesn't seem quite right.

![image](https://user-images.githubusercontent.com/15663460/231038987-93fc18b5-bda0-4231-9180-65136260aec7.png)

**Comment by harshvardhaniimi** [comment]
Thanks for the prompt reply, and apologies for the inconvenience. I blog about things other than R as well, thus creating an R-specific RSS that went a bit wrong. Now, it's fixed.

Here are the links:
1. Link to first one: https://hvsc1708.substack.com/feed
2. Second one: https://rss.app/feeds/x9dPjIxhxqkZpGOL.xml

## Type of Content
- [x] Tutorials - R tutorials for how to use certain packages and tools (usually code is embedded)
- [x]  Insights - Articles that talk about R and data science in general (usually no code embedded)
- [x]  R in Real World - Posts that discuss analyses that use R to analyze real-world data sets
- [ ]  R in Organization - R use cases/events that showcase how organizations are utilizing or integrating R
- [x]  R in Academia - R use cases that showcase how Academia is utilizing R
- [ ]  International - Non-English R related content
- [ ]  Videos and Podcasts - Videos and Podcasts about R
- [x]  Resources - long posts, websites, books, slides, list, cheat sheets, or other learning resources in general that are more officially aggregated as a guide material
- [ ]  Jobs - R Jobs
- [x]  New Packages and Tools - New packages and tools that have been created or published in the past two weeks.
- [x]  Updated Packages - New releases of tools and packages for R
- [ ]  Call for Participation - New R groups, communities or competitions here.
- [x]  Upcoming Events - Interesting R-related events or call for Participation section.
- [ ]  R Project Updates: it belongs here rather than the call for participation because it is about contribution to the R project itself and is a collaboration with R core.

## Checklist
- [x] My content is R-related

**Comment by jonocarroll** [comment]
Hi, I added your two feeds to our list but the more recent entries in both are not strictly R-related. Adding non-R content means we need to filter it out each week, so we would prefer to have R-specific feeds. I notice we do already capture https://www.harsh17.in/blog/index.xml which appears to be from https://www.harsh17.in/categories/r/

For now I will revert to removing the two feeds you listed above.
