### ISSUE TITLE
Clarify which packages are on CRAN, Bioconductor and which are on GitHub etc.

### ISSUE THREAD

**Issue by HenrikBengtsson** [rweekly/rweekly.org#150]
There is big differences in trust, long term archival availability, version control (sic!), ... for a package on CRAN versus a package on a self-hosted website or on GitHub or similar.  Because of this I think would be valuable if packages mentioned on rweekly.org are tagged or structured such that it clear they're not on CRAN or Bioconductor(*).  This helps encourage submitting packages to CRAN, send the message that it makes a difference, while not discouraging GitHub-only packages to be announced here.

(*) The CRAN organization considers both CRAN and Bioconductor as so called "mainstream" repositories (e.g. a package on CRAN may depend on a Bioconductor package without further specifications).

**Comment by qinwf** [comment]
Thanks, great idea. We can add logos to packages, <img src="https://link.rweekly.org/c" width='23'></img> for cran packages, <img src='https://link.rweekly.org/g' width="20"></img> for GitHub packages, <img src="https://link.rweekly.org/b" width="50"></img> for bioc packages.

**Comment by HenrikBengtsson** [comment]
I like that (though some would bring up the R != CRAN argument - but since there's no CRAN logo I'd say the R one is the best option).

**Comment by maelle** [comment]
Why not use a CRAN "badge" like https://ropensci.org/packages/ ?

**Comment by HenrikBengtsson** [comment]
I like. Bioconductor has something similar displaying "in Bioc: 5 years", e.g. http://bioconductor.org/shields/years-in-bioc/illuminaio.svg for http://bioconductor.org/packages/release/bioc/html/illuminaio.html.  The downside of using badges, is that they produce live info, so packages that disappear in the future will have broken links if someone reads an old rweekly post.

Also, I think usage should be sparse to avoid add too much cluttering.  That's why I think just having separate subsections.

**Comment by qinwf** [comment]
The image labels make the draft very verbose. I updated the draft with CRAN and Github only sections to separate the packages. If there are bioc packages, we can also add bioc sections.

https://github.com/rweekly/rweekly.org/blob/gh-pages/draft.md#new-packages

**Comment by maelle** [comment]
Cool! Should we close this now?

**Comment by HenrikBengtsson** [comment]
Looks good to me. Thxs
