### ISSUE TITLE
Link not added in Weekly Newsletter

### ISSUE THREAD

**Issue by deepanshu88** [rweekly/rweekly.org#156]
I submitted a link of my blog to https://rweekly.org/submit. The link is related to data manipulation with R . I submitted it on 16th Jan. I think it should be added to the weekly newsletter today. Is not all the links listed in newsletter? I checked RSS feed. It's correct.

**Comment by qinwf** [comment]
To ensure the experience of R Weekly users, R Weekly reserves the right to select contents. We may reject a submission. Thank you for your understanding.

We will add some guidelines about what may be rejected in the https://github.com/rweekly/rweekly.org/blob/gh-pages/CONTRIBUTING.md
