### ISSUE TITLE
Add RSS feed (duplicate?)

### ISSUE THREAD

**Issue by AlbertRapp** [rweekly/rweekly.org#1605]
Hi everyone :wave: 

I just wanted to add my [blog's RSS feed](https://albert-rapp.de/blog.xml) to the [list of feeds](https://github.com/rweekly/rweekly.org/blob/gh-pages/rss_feeds.csv) (because I forgot way too often to add the blog posts manually.) But for some odd reason, the csv-file has my feed URL in there already though the blog posts are not automatically included in the R Weekly editions :sweat_smile:

Any idea what's going on there? Is there a way for me to fix that? :thinking:

**Comment by jonocarroll** [comment]
I believe it's all working correctly - [this post](https://albert-rapp.de/posts/ggplot2-tips/26_upset_charts/26_upset_charts.html) (upset charts) was included in 2024-W14 (Tutorials). [this post](https://albert-rapp.de/posts/web_dev/05_grid/05_grid.html) (CSS grid) was included in 2024-W15 (Tutorials). The next post on your blog was published April 7 and we released 2024-W15 on the 8th. We curate issues over the weekend, so we recommend submitting during the week

https://github.com/rweekly/rweekly.org/blob/b2befd1a1cd837670fcf4b3a0f9fc3cc6059ba8a/README.md?plain=1#L47-L51

but RSS-sourced posts may not make our curation deadline.

Our automated feed fetching shows that your posts are coming through 

https://github.com/rweekly/rweekly.org/blob/b2befd1a1cd837670fcf4b3a0f9fc3cc6059ba8a/curatinator_latest.md?plain=1#L36

and the next pull of those will occur this weekend (capturing 10 days of posts, so will include your two latest posts) however I'd like to clarify that the RSS feeds and PRs are merely sources for our editors; there is no notion of "automatically included in the R Weekly editions" - the issues are human-curated for relevance and as such, inclusion of any post is at the discretion of the editor that week.

**Comment by AlbertRapp** [comment]
Ah thank you @jonocarroll that's fantastic news. Totally my bad for not realizing it's already working. :see_no_evil:
