### ISSUE TITLE
dead link on "jobs"

### ISSUE THREAD

**Issue by defuneste** [rweekly/rweekly.org#1612]
The "jobs" link https://forum.posit.co/c/jobs/ is dead

a quick search give me this one: https://forum.posit.co/c/news/jobs/20

(unsure if this is teh good one!)

Thanks a lot for the new letter it is great!

**Comment by jonocarroll** [comment]
Thanks for the report. I'm currently getting '502 Bad Gateway' on all of https://forum.posit.co/ so I'm not sure what the "good" link actually is. Once we can identify that we'll update our template.

**Comment by defuneste** [comment]
Hey @jonocarroll apparently the post  has been taken down: 

> @Olivier Leroy, @Trevin Flickinger Yes, that’s right! We only had 4-5 posts a year, so it’s been taken down. 

From @ivelasq

**Comment by jonthegeek** [comment]
Posit officially retired the page. I submitted a "fix" for this same issue this morning, independently as #1614
