### ISSUE TITLE
Display the list of RSS Feeds for R Weekly Live

### ISSUE THREAD

**Issue by qinwf** [rweekly/rweekly.org#216]
see https://twitter.com/StatnMap/status/965212788888162304

**Comment by qinwf** [comment]
maybe related https://twitter.com/rushworth_a/status/963752449378062336

**Comment by qinwf** [comment]
see https://rweekly.org/feedlist.html

**Comment by maelle** [comment]
fantastic, you should tweet to announce it if not done :-)
