### ISSUE TITLE
Atom feed doesn't validate

### ISSUE THREAD

**Issue by wdenton** [rweekly/rweekly.org#28]
### What

I noticed the feed wasn't showing up in my reader (Planet Venus), and checked it on the W3C validator:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frweekly.org%2Fatom.xml
### Ideas about How to Solve It

Set an email address in the config, and add a trailing slash to the id.

**Comment by qinwf** [comment]
Thanks! Now it passes the validator. 

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frweekly.org%2Fatom.xml
