### ISSUE TITLE
Date format: Use ISO YYYY-MM-DD

### ISSUE THREAD

**Issue by HenrikBengtsson** [rweekly/rweekly.org#323]
R Weekly uses 'Release Date: 2018-6-18'.  There exist no such date format (YYYY-M-DD) and as a data science community I think we should be good citizens and not use non-standard date and timestamps.  I recommend using the ISO standard (YYYY-MM-DD), e.g. 'Release Date: 2018-06-18'.   From [xkcd](https://xkcd.com/1179/):

<img width="392" alt="iso_8601_2x" src="https://user-images.githubusercontent.com/1616850/41816175-efe09c54-7732-11e8-8509-be2863a18d94.png">

**Comment by qinwf-nuan** [comment]
Thanks, great point, will use it in the upcoming releases.

**Comment by qinwf** [comment]
Thanks, great point, will use it in the upcoming releases.

**Comment by HenrikBengtsson** [comment]
FYI, https://rweekly.org/live is still using the YYYY-M-D format.

**Comment by HenrikBengtsson** [comment]
Bump/friendly reminder

**Comment by jonmcalder** [comment]
Thanks for the reminder @HenrikBengtsson - this has now been addressed.

**Comment by HenrikBengtsson** [comment]
Beautiful. Now I can finally be able to sleep at night ;)
