### ISSUE TITLE
Seems paginator didn't work in home page

### ISSUE THREAD

**Issue by BruceZhaoR** [rweekly/rweekly.org#34]
https://github.com/rweekly/rweekly.org/blob/gh-pages/index.html#L22 

I don't know how to solve it , please CC @qinwf

**Comment by qinwf** [comment]
These pages now use infinite scrolling with `jquery.jscroll` .

Can you please open the home page and then open inspect element window to check the status of this js file https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.3.5/jquery.jscroll.min.js .

**Comment by BruceZhaoR** [comment]
sorry, my mistake~
