### ISSUE TITLE
Reddit discussion?

### ISSUE THREAD

**Issue by amrrs** [rweekly/rweekly.org#382]
Are we allowed to add Reddit discussions like this?

[Am I crazy for loving R as a general-purpose high-level language?](https://www.reddit.com/r/rstats/comments/9hviwd/am_i_crazy_for_loving_r_as_a_generalpurpose/)

**Comment by qinwf-nuan** [comment]
Yes, https://www.reddit.com/r/rstats is OK.

**Comment by qinwf** [comment]
Yes, https://www.reddit.com/r/rstats is OK.

**Comment by amrrs** [comment]
Thanks, can you please say which is the appropriate section for this ?

**Comment by amrrs** [comment]
Thanks for adding it!
