### ISSUE TITLE
Conferences and user groups

### ISSUE THREAD

**Issue by csgillespie** [rweekly/rweekly.org#390]
I maintain a list of user groups and conferences: https://github.com/jumpingrivers/meetingsR When a conference or group is added to the pages, I automatically (via Travis) update CSV files at https://jumpingrivers.github.io/meetingsR/the-data.html

Two thoughts:

# Conferences

It's fairly easy to get upcoming conferences. For example,
```
library(tidyverse)
read_csv("https://jumpingrivers.github.io/meetingsR/events.csv") %>%
  mutate(d = lubridate::ymd(paste(year, month, "01", sep = "-"))) %>%
  filter(d < today() + months(3)) %>%
  filter(d > today()) %>%
  arrange(d) %>%
  View()
```

# User groups

Looking at the commits, it would be possible to determine new useR groups in the world. Straightforward to see if the repo has changed in the last week, but probably needs a human to parse the logs.

**Comment by qinwf** [comment]
Thanks! Will look into this next week.

**Comment by csgillespie** [comment]
Happy to tweak the data script as necessary.

**Comment by qinwf** [comment]
Added the link in https://www.rweekly.org/2018-43.html#UpcomingEventsin3Months

**Comment by csgillespie** [comment]
@qinwf Should we close this issue?
