### ISSUE TITLE
issue 2 : little bug about image links?

### ISSUE THREAD

**Issue by BruceZhaoR** [rweekly/rweekly.org#4]
`![[Images as x-axis labels](http://jcarroll.com.au/2016/06/03/images-as-x-axis-labels-updated/)](https://i2.wp.com/jcarroll.com.au/wp-content/uploads/2016/06/GDP_updated.png)`

[raw code](https://rawgit.com/rweekly/rweekly.org/gh-pages/_posts/2016-6-6-issue-2.md) Tutorials -> the first one and so on

should be :  `[![Images as x-axis labels](https://i2.wp.com/jcarroll.com.au/wp-content/uploads/2016/06/GDP_updated.png)](http://jcarroll.com.au/2016/06/03/images-as-x-axis-labels-updated/)]`  ?

@qinwf  cc

**Comment by BruceZhaoR** [comment]
cause issue 1 was the format that you click  on the image to jump to the related post.  I'm not sure this should be applied to issue 2.

**Comment by qinwf** [comment]
Yes, these links should be updated.
