### ISSUE TITLE
use jsdelivr CDN?

### ISSUE THREAD

**Issue by BruceZhaoR** [rweekly/rweekly.org#411]
jsDelivr is a free, fast, and reliable Open Source CDN for npm and GitHub. 

https://www.jsdelivr.com 

Migrating from RawGit to jsDelivr : https://www.jsdelivr.com/rawgit

ping @qinwf

**Comment by BruceZhaoR** [comment]
How about using jsdelivr CDN for images in 2019 rweekly issues?

**Comment by qinwf** [comment]
I think use a direct link to https://github.com/rweekly/image is ok.

We do not know when will jsdelivr stop working. If it stop working, we will need to update all exisiting  jsdelivr links.

https://github.com/rweekly/image will works fine for a long time.
