### ISSUE TITLE
draft.md: seems to contain old info + new info is lost

### ISSUE THREAD

**Issue by HenrikBengtsson** [rweekly/rweekly.org#459]
https://github.com/rweekly/rweekly.org/blob/gh-pages/draft.md, e.g. Section 'Upcoming Events in 3 Months'

**Comment by jonmcalder** [comment]
Thanks for the heads up @HenrikBengtsson - addressed (hopefully?) in https://github.com/rweekly/rweekly.org/commit/f12ee6d19457515ddd53e72dbca7405493a8c921
