### ISSUE TITLE
RSS feed only displays newsletter titles

### ISSUE THREAD

**Issue by lillemets** [rweekly/rweekly.org#461]
I use the Rweekly RSS feed in Zotero. At least in Zotero, the feed only contains the weekly newsletter titles (e.g. *R Weekly 2019-09 Lego, group_split*) and nothing else. As such, it's pretty much useless. The [RSS feed of R-bloggers](https://feeds.feedburner.com/RBloggers) feeds actual article titles with creator names and abstracts. Could the RSS feed of Rweekly be fixed so that it behaves in a similar way?

**Comment by qinwf** [comment]
It looks ok in feedburner http://feeds.feedburner.com/rweekly-main

It is the same as https://rweekly.org/atom.xml

**Comment by lillemets** [comment]
> It looks ok in feedburner http://feeds.feedburner.com/rweekly-main

The actual submissions are displayed in Feedburner but not in feed readers (at least the few I tried). If you look at the structure of the feed, it consists of weekly newsletters. Thus, feed reader applications only serve the titles of these newsletters. That is unlike the [feed of R-bloggers](https://feeds.feedburner.com/RBloggers), in which case the items in feed are submissions instead of weekly summaries. It would be nice if Rweekly.org feed functioned similarly.

**Comment by qinwf** [comment]
We are not authorized to post the detail content from different blog posts. 

You can also try these two feeds from https://rweekly.org/live

with new CRAN packages - https://feeds.feedburner.com/rweekly-live

only blog posts - https://feeds.feedburner.com/rweeklylive

**Comment by lillemets** [comment]
> only blog posts - https://feeds.feedburner.com/rweeklylive

That is what I was looking for. Problem solved. Thank you!
