### ISSUE TITLE
Presentation (Doubt - if this is allowed? )

### ISSUE THREAD

**Issue by amrrs** [rweekly/rweekly.org#462]
https://github.com/amrrs/RinTheRealWorld 

Just wanted to know if the presentation in this repo can be submitted?

If so, please suggest the category.

**Comment by qinwf** [comment]
Yes. It will be in the resources section. 

By the way, it will better to write a blog post to explain the slides.

**Comment by maelle** [comment]
> By the way, it will better to write a blog post to explain the slides.

+1, a bit more work, but one does most of the thinking when preparing the talk, and the impact is greater.

**Comment by amrrs** [comment]
Thanks @qinwf  and @maelle  for the comments. I agree it's helpful but not sure if I'd be able to do it. Anyways I missed submitting this link to the last week's, so closing this issue!
