### ISSUE TITLE
Feed seem to be broken

### ISSUE THREAD

**Issue by EdwinTh** [rweekly/rweekly.org#468]
I noticed that new blogs of my [site](https://edwinth.github.io/) are no longer appearing at rweekly. I reassigned my blog at Submit, but this does not seem to change it. Not sure if it is something on your end or mine, but hopefully we can figure it out together.

Thanks

**Comment by qinwf** [comment]
Thank you for your report. 

R Weekly server is not parsing the feed correctly and set it to disabled. We update the url to use FeedBurner to parse the feed and now it is working now. 

Please check https://rweekly.org/live to see the result.

**Comment by EdwinTh** [comment]
Sorry for coming back this late. The feed is working again, thanks for your trouble!
