### ISSUE TITLE
Bug Report: URL fails to open.

### ISSUE THREAD

**Issue by JiaxiangBU** [rweekly/rweekly.org#484]
At the latest page https://rweekly.org/2019-18.html , this URL [runcharter ( johnmackintosh.com )](https://www.johnmackintosh.com/2019-04-30-runcharter/) fails to open (404).

I click the GitHub User Page, but the author @johnmackintosh doesn't open the issue button, [here](https://github.com/johnmackintosh/johnmackintosh.github.io).

Thus, I only report it here now. Hope to reach out @johnmackintosh to see what is going on.

**Comment by jonmcalder** [comment]
Thanks for opening this issue - the url was definitely valid and working until up until the time of this weeks release. It looks like @johnmackintosh changed the published status recently (see [here](https://github.com/johnmackintosh/johnmackintosh.github.io/commit/426b41049c17b02b8de21461748d946053b8c410)).

**Comment by JiaxiangBU** [comment]
Thanks, @jonmcalder , from the url you post, I find this [blog](https://github.com/johnmackintosh/johnmackintosh.github.io/blob/master/_posts/2019-04-30-runcharter.md) and the related package https://www.johnmackintosh.com/runcharter/
