### ISSUE TITLE
Links (link.rweekly.org/*) not working through Feedburner RSS feed

### ISSUE THREAD

**Issue by RCura** [rweekly/rweekly.org#577]
In the feedburner feed of the live stream (https://feeds.feedburner.com/rweekly-live), all new items are linked with a short-link that does'nt work.

For example, on today's feed :
![image](https://user-images.githubusercontent.com/807703/67010990-0730cf00-f0ef-11e9-9e96-059317b5c779.png)

This latest article ("ubiquity PKPD, PBPK, and Systems Pharmacology Modeling Tools") links to http://feedproxy.google.com/~r/rweekly-live/~3/mQpzLIiX69M/fuq , which is resolved as https://link.rweekly.org/fuq , which in turn resolve to an error :

![image](https://user-images.githubusercontent.com/807703/67011156-52e37880-f0ef-11e9-8b19-634cc3213a71.png)

Thus, this live feed can not be used as is, and requires to go to rweekly live page each time to access the proper links.

**Comment by qinwf** [comment]
Thank you for your report and really sorry for the late reply. I missed this issue.

I updated the feed url for the future updates. It will use the original url and skip https://link.rweekly.org.

**Comment by maelle** [comment]
can this be closed?
