### ISSUE TITLE
Does the submission form still work?

### ISSUE THREAD

**Issue by atheriel** [rweekly/rweekly.org#585]
I routinely submit blog posts through the online form but never see them added to the weekly page -- is this possibly due to an error on my part? Is there some way to get a confirmation that submissions have been accepted? Or is it recommended to use GitHub instead?

**Comment by jonocarroll** [comment]
Could you please provide an example of one you submitted? I can check the logs to see if it appears there. The issues are human-curated each week, so it's possible that a submitted link was deemed out of scope, but an example will help us figure that out.

**Comment by qinwf** [comment]
Yes, it works. 

You submitted the link 2019/11/10 2:08:30 - An Autoconf Primer for R Package Authors 

and it will be on the next issue.

**Comment by atheriel** [comment]
Oh, I hadn't considered it might be more than a week. Thanks for the clarification!
