### ISSUE TITLE
Blogpost repeated every week

### ISSUE THREAD

**Issue by JoseEchave** [rweekly/rweekly.org#587]
Hello, I sent a blog to the webpage three weeks ago, and I realized that this is the 3rd time in a row that It appears.

**Comment by JoseEchave** [comment]
This is the link: https://jechave.com/post/12-months-of-restaurants/

**Comment by jonocarroll** [comment]
Apologies - we have a set of tools for gathering prospective links and somehow this got either re-submitted or was persistent in our cache. We're looking into removing posts which have already appeared. Thanks for the heads up.
