### ISSUE TITLE
conf.rweekly.org out of date

### ISSUE THREAD

**Issue by HeidiSeibold** [rweekly/rweekly.org#634]
conf.rweekly.org seems a bit out of date, which was a bit confusing to me.

![image](https://user-images.githubusercontent.com/14146757/74422757-64dfe880-4e4f-11ea-9945-4d844244acef.png)

Maybe it would be a good idea to link to https://jumpingrivers.github.io/meetingsR/events.html? (cc @csgillespie)
I see you are already doing that in https://rweekly.org/#UpcomingEventsin3Months

**Comment by csgillespie** [comment]
If you feel really clever, you could grab data from https://github.com/jumpingrivers/meetingsR/blob/gh-pages/events.csv That way you could always show the next events.

Whenever a new event is added, this CSV file gets updated by travis

**Comment by qinwf** [comment]
Thanks.  conf.rweekly.org was archived. 

There is an updated list of events from https://jumpingrivers.github.io/meetingsR/
