### ISSUE TITLE
Proposal: @rweekly_submit twitter account

### ISSUE THREAD

**Issue by jonocarroll** [rweekly/rweekly.org#636]
(posted here rather than internal forums to encourage public engagement)

What do we think about having a twitter account purely for submissions? Found a link? Reply and tag @rweekly_submit - we can scrape the mentions weekly, resolve the t.co links, and de-duplicate for a new batch of submissions.

**Comment by jonocarroll** [comment]
Squatting on this account just in case: https://twitter.com/rweekly_submit

**Comment by qinwf** [comment]
For now, all tweets that mention @rweekly_org and @rweekly_live will go to slack #twitter channel.

There are only a few tweets every week. If we add a third account, it may not be easy to manage all these accounts. 

We can reuse @rweekly_live or @rweekly_org account for this task?

**Comment by jonocarroll** [comment]
(sorry, missed this reply)

I should probably keep a closer eye on that channel. My goal for this was to have a dedicated place for submit tags. I feel a lot of of people tag rweekly_org when recommending it. I'm happy to admin rweekly_submit if you like.

**Comment by qinwf** [comment]
Yes, that is great. We can make the process easier and documented on the web page.
