### ISSUE TITLE
Release date for 2020-10 needs removing

### ISSUE THREAD

**Issue by jonocarroll** [rweekly/rweekly.org#657]
`Release Date: 2020-00-00` appears below the filter box, but we have the actual post date above it anyway.

**Comment by qinwf** [comment]
updated in https://github.com/rweekly/rweekly.org/commit/eb60605255519c1a28b47e1b454879f9a89648cd

**Comment by ColinFay** [comment]
Sorry folks, I was on a plane back from satRday Johannesburg, thanks for taking care of that!

**Comment by qinwf** [comment]
Have a good rest. 😄👍
