### ISSUE TITLE
Articles not appearing on https://rweekly.org/live

### ISSUE THREAD

**Issue by AntoineSoetewey** [rweekly/rweekly.org#658]
Dear,

I submitted the RSS feed of my blog (https://www.statsandr.com/index.xml) a couple of months ago.
However, I see that the last article on your site is dated February 17th. I've posted several since then.

Do you have any idea why the articles are no longer published?

Thank you in advance for your answer.

Best,
Antoine

**Comment by qinwf** [comment]
https://feeds.feedburner.com/statsandr/llLE

<img width="921" alt="截屏2020-03-18下午9 24 22" src="https://user-images.githubusercontent.com/7472151/76965234-e8b15700-695e-11ea-8b65-401e41234715.png">

The feed is too big. Google is not processing the new items.

Please create a smaller feed.

**Comment by AntoineSoetewey** [comment]
Thanks for your answer.

Is this feed better: https://www.statsandr.com/tags/r/index.xml ?
It contains only the articles with the R tag.

**Comment by qinwf** [comment]
No. Please provide a feed without the detail content. Google will process the file when it is smaller than 1024K.

**Comment by AntoineSoetewey** [comment]
Ok I understand, sorry about that.

Now it seems that the feed only shows a summary: https://simplepie.org/demo/?feed=https%3A%2F%2Fwww.statsandr.com%2Findex.xml. Is that better?

**Comment by qinwf** [comment]
That is not a valid RSS feed.

R Weekly Live monitors many feeds. If all of these feeds are 2MB or more, it will require the R Weekly Live to read 1GB+ data on each interval for RSS update checking.

So the server uses Google Feedburner to avoid the unexpected huge traffic. Google Feedburner will limit the RSS feed size to 1024kb.

**Comment by AntoineSoetewey** [comment]
Thanks again for your reply.

I have created a new feed through google feed burner: http://feeds.feedburner.com/statsandr/zjAx

Is that one ok?

My apologies for all these questions, I’m quite new to this.

Best,
Antoine

**Comment by qinwf** [comment]
Thanks, updated the feed.
