### ISSUE TITLE
broken link to article on home page

### ISSUE THREAD

**Issue by merlinoa** [rweekly/rweekly.org#693]
The link "shinyFeedback 0.2.0 CRAN" on "https://rweekly.org/" has a broken link.  Somehow the link got prefixed with the word "release" so instead of linking to "https://www.tychobra.com/posts/2020-04-28-shinyfeedback-0.2.0-on-cran/" it links to "releasehttps://www.tychobra.com/posts/2020-04-28-shinyfeedback-0.2.0-on-cran/".  

This was probably my error when I submitted the article.

**Comment by tonyelhabr** [comment]
Thanks for the note. I fixed it.

**Comment by merlinoa** [comment]
Thanks!
