### ISSUE TITLE
Duplicate posts in live feed

### ISSUE THREAD

**Issue by gadenbuie** [rweekly/rweekly.org#698]
Hi all, I noticed that one of my recent posts appeared twice in the live feed: 

![image](https://user-images.githubusercontent.com/5420529/81407536-95ab8300-9109-11ea-9446-b7695769ddd6.png)

I checked the [feedlist](https://live.rweekly.org/feedlist.json) and my blog feed only appears once. I also checked [feedburner](http://feeds.feedburner.com/ROnGarrickAden-Buie) and the post only appears once there as well.

Is there anything on my end that I should adjust?

**Comment by qinwf** [comment]
Thanks. The duplicate post was removed.
