### ISSUE TITLE
about rstudio::global

### ISSUE THREAD

**Issue by qinwf** [rweekly/rweekly.org#750]
status update here

**Comment by qinwf** [comment]
https://blog.rstudio.com/2020/07/17/rstudio-global-call-for-talks/

how to apply:

```
To apply, as well as the usual title and abstract, you’ll need to create a 60 second video that introduces you and your proposed topic. In the video, you should tell us who you are, why your topic is important, and what attendees will take away from it. We’re particularly interested in hearing about:

How you’ve used R (by itself or with other technologies) to solve a challenging problem.

Your favourite R package (whether you wrote it or not) and how it significantly eases an entire class of problems or extends R into new domains.

Your techniques for teaching R to help it reach new domains and new audiences.

Broad reflections on the R community, R packages, or R code.

Applications close August 14, and you’ll hear back from us in mid September.
```

format:


> Talks will be 20 minutes long and recordings will be due in early December, and you’ll also be part of the live program in January; details TBD. We’ll provide support to make sure that everyone can produce a high quality video regardless of circumstances.

**Comment by qinwf** [comment]
## Title

Lifelong Learning with R Weekly

## Abstract and Intro Video

Hi, everyone. My name is Wolfram King. I am from the R Weekly team.

R Weekly is a weekly newsletter with many great R blogs post, tutorials, and other formats of resources.

R Weekly wants to keep track of these great things in the R community and make it more accessible to everyone.

This is a warm and welcoming place. The team welcomes everyone who wants to contribute to the R community.

In this talk I will cover these 6 topics:

1. How to use the R Weekly website
2. Why I created R Weekly
3. How to Contribute to R Weekly
4. How to release a new post
5. How to join the team
6. Learning from building the community

**Comment by maelle** [comment]
Some suggestions.

1. Say you are R Weekly founder, and when you founded it.
2. Rephrase the 6 topics to make it sound less like a list. E.g.

"In this talk I will offer my unique insight as R Weekly founder. I will reveal how and why I founded this successful collaborative newsletter. My talk will also help R users better take advantage of our platform (how to best use our website? how to share links?); motivate some of them to join our editorial team; and inspire others to launch such knowledge sharing projects!"

**Comment by maelle** [comment]
(these are only _suggestions_!!)

**Comment by qinwf** [comment]
intro video 

https://www.youtube.com/watch?v=PtbFqluymgU&feature=youtu.be

**Comment by jonocarroll** [comment]
Looks great, well done!

**Comment by maelle** [comment]
Awesome, well done! It's a bit too long though https://twitter.com/hadleywickham/status/1290707968774873089

Also, you could pin an R Weekly sticker to your shirt or on the wall behind you! :grin:
