### ISSUE TITLE
Minor style suggestions

### ISSUE THREAD

**Issue by eddelbuettel** [rweekly/rweekly.org#81]
### What

Some of your section headings are not quite common English. 

### Ideas about How to Solve It

Insert a 'the' to yield

- R in the Real World

Insert a plural 's' to yield

- R in Organizations

**Comment by qinwf** [comment]
Thanks!

**Comment by eddelbuettel** [comment]
You may want to run it by a native speaker.  English is only my 2nd language too...but I lived in English speaking countries for quite some time now.
