### ISSUE TITLE
post not published

### ISSUE THREAD

**Issue by shannonpileggi** [rweekly/rweekly.org#866]
Hi R-Weekly team!  👋 Thank you for all of the fantastic work you do, I really look forward to each weekly issue!

I have submitted my blog to the RSS feed, and my posts are coming into the live feed.  I did have a [previous issue](https://github.com/rweekly/rweekly.org/issues/794) where one of my posts was not published, but I realized that was because I published my post on the weekend which isn't best for you editorial process.  So I am sure to publish Monday - Friday now!

My [most recent blog post](https://www.pipinghotdata.com/posts/2021-02-15-gganimating-a-geographic-introduction/) was published on Monday, Feb 15, and it did  not appear in the [2021-W08](https://rweekly.org/2021-W08.html?utm_source=feedburner&utm_medium=email&utm_campaign=Feed%3A+rweekly+%28RWeekly.org+-+Weekly+Updates+from+the+R+Community%29) issue posted on Monday, Feb 22. Or if it did get published and I missed it please let me know! 🧐

Is there an editorial process that decides which contributions get included? Or should all content submitted through RSS feed be included? Or is there anything I can be doing differently to ensure inclusion of my content? 

Thank you! 🙏🏻

**Comment by qinwf** [comment]
https://twitter.com/rweekly_live/status/1361270211723341824 rweekly_live tweeted about this post. I will add the post to the draft of the next week. 

Thank you for the report.

**Comment by shannonpileggi** [comment]
I did miss the tweet, thanks for letting me know!

And thanks for your help!
