### ISSUE TITLE
Add virtuals events to the release

### ISSUE THREAD

**Issue by mcanouil** [rweekly/rweekly.org#889]
Hi,

currently in the "Upcoming Events in 3 Months" section, the URL to  jumpingrivers.github.io  point to IRL events only, while there is a "virtual-events" section as well: https://jumpingrivers.github.io/meetingsR/virtual-events.html

Would it be possible to also add virtual events in each release?

**Comment by jonmcalder** [comment]
Thanks for the heads up - since the events link doesn't yet have any content for 2021, have replaced it with the virtual events link for now.
