### ISSUE TITLE
updated website; RSS link changed

### ISSUE THREAD

**Issue by shannonpileggi** [rweekly/rweekly.org#925]
Hi lovely R weekly crew!

I updated my website and my RSS feed has changed. I believe it was formerly 

`https://www.pipinghotdata.com/index.xml `

and now it is currently

`https://www.pipinghotdata.com/blog.xml`

Should I use the [submit form](https://rweekly.org/submit) to update, or is it better for you to do elsewhere?

Thank you!

**Comment by jonocarroll** [comment]
I'll update it in our system - thank you!

**Comment by shannonpileggi** [comment]
Super, thanks!

**Comment by jonocarroll** [comment]
Updated. Thank you!

**Comment by shannonpileggi** [comment]
Thank you!
