### ISSUE TITLE
2021-10-11 post not published

### ISSUE THREAD

**Issue by shannonpileggi** [rweekly/rweekly.org#976]
Hi RWeekly! I have so much appreciation for all that you do to bring R news to the community - thank you for all of your efforts!

I did have a [blog post published on Monday 2021-10-11](https://www.pipinghotdata.com/posts/2021-10-11-estimating-correlations-adjusted-for-group-membership/) & I can see that it went through the live feed; however, the post did not end up in [RWeekly2021-W42](https://rweekly.org/#RWeekly2021-W42VSCode,rpp,fillregionbetweenggplot2lines).

Would it be possible to include this post in the next issue? I'm not too concerned with this individual post, but I do want to strive to have diverse individuals represented in the RWeekly content.

Thank you for considering!

(And if it is there and I missed it, my sincere apologies! This is me 🧐 looking through everything!)

**Comment by Ryo-N7** [comment]
Hi Shannon,

Since it was published on Monday, I'm guessing it got caught "in between" issues when an issue is finalized/published and when the new editor for the next week takes over. 

I've added it in for this week: https://github.com/rweekly/rweekly.org/blob/gh-pages/draft.md

Thanks!

**Comment by shannonpileggi** [comment]
Super, thank you so much, I appreciate it!
